all:
  hosts:
    cp1:
      ansible_host: 51.250.64.33
      ansible_user: devuser
    node1:
      ansible_host: 130.193.48.89
      ansible_user: devuser
    node2:
      ansible_host: 51.250.22.62
      ansible_user: devuser      
  children:
    kube_control_plane:
      hosts:
        cp1:
    kube_node:
      hosts:
        node1:
        node2:
    etcd:
      hosts:
        cp1:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}